### ISSUE TITLE
Trying to pass a test fails

### ISSUE THREAD

**Issue by hakontro** [bkkas/elhub-python-sdk#8]
* ElHub Python SDK version: current
* Python version: 3.10
* Operating System: Mac Ventura 13

### Description

Trying to pass  `tests/tests_examples/ag622-01-actor-test.py` fails.

### What I Did

I've set up key/cert file, and I'm using the wsdl that comes with the most recent version of the SDK. I've also started the test on Edielportalen, with the correct `TEST_METER_IDENTIFICATORS` that was given to me by ElHub. (These should perhaps be removed from the codebase and replaced by environment variables I guess?) Seem personal to Volte, like the rest of the content in `tests/tests_examples/config.py`.

Not sure how to move forward here, as far as I can tell my key/cert files are read correctly into the zeep client.

```
ERROR:root:Security error
Traceback (most recent call last):
  File "/Users/hakontro/code/elhub-python-sdk/elhub_sdk/third_party.py", line 117, in request_action
    response = client.service.UpdateThirdPartyAccess(eh_request)
  File "/Users/hakontro/Library/Caches/pypoetry/virtualenvs/elhub-python-sdk-EOAmAs5P-py3.10/lib/python3.10/site-packages/zeep/proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "/Users/hakontro/Library/Caches/pypoetry/virtualenvs/elhub-python-sdk-EOAmAs5P-py3.10/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 135, in send
    return self.process_reply(client, operation_obj, response)
  File "/Users/hakontro/Library/Caches/pypoetry/virtualenvs/elhub-python-sdk-EOAmAs5P-py3.10/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 229, in process_reply
    return self.process_error(doc, operation)
  File "/Users/hakontro/Library/Caches/pypoetry/virtualenvs/elhub-python-sdk-EOAmAs5P-py3.10/lib/python3.10/site-packages/zeep/wsdl/bindings/soap.py", line 329, in process_error
    raise Fault(
zeep.exceptions.Fault: Security error
```

**Comment by hakontro** [comment]
Also: @jgc31416 is it possible to get access to create PRs to this repo? Found some minor typos I'd like to contribute fixes for :)

**Comment by hakontro** [comment]
Mistake was on my end, progress is being made :)
